INSERT INTO location values 
    ("São Paulo", "Brasil"),
    ("Rio Branco", "Brasil"),
    ("Maceió", "Brasil"),
    ("Macapá", "Brasil"),
    ("Manaus", "Brasil"),
    ("Salvador", "Brasil"),
    ("Fortaleza", "Brasil"),
    ("Brasília", "Brasil"),
    ("Vitória", "Brasil"),
    ("Goiânia", "Brasil"),
    ("São Luís", "Brasil"),
    ("Cuiabá", "Brasil"),
    ("Campo Grande", "Brasil"),
    ("Belo Horizonte", "Brasil"),
    ("Belém", "Brasil"),
    ("João Pessoa", "Brasil"),
    ("Curitiba", "Brasil"),
    ("Recife", "Brasil"),
    ("Teresina", "Brasil"),
    ("Rio de Janeiro", "Brasil"),
    ("Natal", "Brasil"),
    ("Porto Alegre", "Brasil"),
    ("Porto Velho", "Brasil"),
    ("Boa Vista", "Brasil"),
    ("Aracaju", "Brasil"),
    ("Florianópolis", "Brasil"),
    ("Palmas", "Brasil");